### PR TITLE
FAQS: 500/403 errors -> Kramdown + renaming + typos

### PR DESCRIPTION
**Pull request by NicolasGraph**
Is that ok?

### CODE REVIEW

**Comment by philwareham** [comment]
This is good thanks, I did do a couple of minor tweaks afterwards but if you'd like to proceed (and I'll proof read) then that would be very helpful. Speeds things up a lot.

**Comment by NicolasGraph** [comment]
Ok, I'll continue; thanks Phil.

**Comment by philwareham** [comment]
You might want to wait until @Bloke has audited which FAQ are to stay and which are to be removed/moved before continuing.

**Comment by NicolasGraph** [comment]
That's what I'll do; thanks.

**Pull request merged**
